services:
  database:
    image: mysql:8.2.0
    environment:
      MYSQL_DATABASE: "jpademo"
      MYSQL_USER: "test-user"
      MYSQL_PASSWORD: "test-password"
      MYSQL_ROOT_PASSWORD: "test-root-password"
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data: